-- Tạo các roles cho dự án
CREATE OR REPLACE ROLE TPCH_ADMIN;        -- Quản trị toàn bộ
CREATE OR REPLACE ROLE TPCH_DEVELOPER;    -- Developer: Load data, transform
CREATE OR REPLACE ROLE TPCH_ANALYST;      -- Analyst: Query, report
CREATE OR REPLACE ROLE TPCH_VIEWER;       -- Viewer: Chỉ xem reports
-- Tạo database cho dự án
CREATE OR REPLACE DATABASE TPCH_ANALYTICS_DB;
-- Tạo các schemas
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.STAGING; -- Dữ liệu gốc từ files
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.ANALYTICS; -- Dữ liệu đã biến đổi
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.REPORTS; -- Báo cáo cuối cùng
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.UDFS; -- User-define function
-- Grant quyền phù hợp cho các roles trên schemas
--- Admin role 
GRANT ALL PRIVILEGES ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN;
--- Developer role 
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
--- Analyst role 
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;
--- Viewer role 
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;

-- Tạo internal stage cho data files
CREATE OR REPLACE STAGE TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE;
-- Grant quyền trên stage
GRANT READ, WRITE ON STAGE TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE TO ROLE TPCH_DEVELOPER;
GRANT READ ON STAGE TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE TO ROLE TPCH_ANALYST;
-- Kiểm tra stage
LIST @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE;
-- Tạo các bảng raw
-- B1: Chọn schema chứa các bảng raw 
USE DATABASE TPCH_ANALYTICS_DB;
USE SCHEMA STAGING;
-- B2: Tạo các bảng raw
-- Bảng 1: REGION
CREATE OR REPLACE TABLE REGION (
  R_REGIONKEY NUMBER(38,0),
  R_NAME VARCHAR(25),
  R_COMMENT VARCHAR(152)
);
-- Bảng 2: NATION
CREATE OR REPLACE TABLE NATION (
  N_NATIONKEY NUMBER(38,0),
  N_NAME VARCHAR(25),
  N_REGIONKEY NUMBER(38,0),
  N_COMMENT VARCHAR(152)
);
-- Bảng 3: CUSTOMER
CREATE OR REPLACE TABLE CUSTOMER (
  C_CUSTKEY NUMBER(38,0),
  C_NAME VARCHAR(25),
  C_ADDRESS VARCHAR(40),
  C_NATIONKEY NUMBER(38,0),
  C_PHONE VARCHAR(15),
  C_ACCTBAL NUMBER(12,2),
  C_MKTSEGMENT VARCHAR(10),
  C_COMMENT VARCHAR(117)
);
-- Bảng 4: SUPPLIER
CREATE OR REPLACE TABLE SUPPLIER (
  S_SUPPKEY NUMBER(38,0),
  S_NAME VARCHAR(25),
  S_ADDRESS VARCHAR(40),
  S_NATIONKEY NUMBER(38,0),
  S_PHONE VARCHAR(15),
  S_ACCTBAL NUMBER(12,2),
  S_COMMENT VARCHAR(101)
);
-- Bảng 5: PART
CREATE OR REPLACE TABLE PART (
  P_PARTKEY NUMBER(38,0),
  P_NAME VARCHAR(55),
  P_MFGR VARCHAR(25),
  P_BRAND VARCHAR(10),
  P_TYPE VARCHAR(25),
  P_SIZE NUMBER(38,0),
  P_CONTAINER VARCHAR(10),
  P_RETAILPRICE NUMBER(12,2),
  P_COMMENT VARCHAR(23)
);
-- Bảng 6: PARTSUPP
CREATE OR REPLACE TABLE PARTSUPP (
  PS_PARTKEY NUMBER(38,0),
  PS_SUPPKEY NUMBER(38,0),
  PS_AVAILQTY NUMBER(38,0),
  PS_SUPPLYCOST NUMBER(12,2),
  PS_COMMENT VARCHAR(199)
);
-- Bảng 7: ORDERS
CREATE OR REPLACE TABLE ORDERS (
  O_ORDERKEY NUMBER(38,0),
  O_CUSTKEY NUMBER(38,0),
  O_ORDERSTATUS VARCHAR(1),
  O_TOTALPRICE NUMBER(12,2),
  O_ORDERDATE DATE,
  O_ORDERPRIORITY VARCHAR(15),
  O_CLERK VARCHAR(15),
  O_SHIPPRIORITY NUMBER(38,0),
  O_COMMENT VARCHAR(79)
);
-- Bảng 8: LINEITEM
CREATE OR REPLACE TABLE LINEITEM (
  L_ORDERKEY NUMBER(38,0),
  L_PARTKEY NUMBER(38,0),
  L_SUPPKEY NUMBER(38,0),
  L_LINENUMBER NUMBER(38,0),
  L_QUANTITY NUMBER(12,2),
  L_EXTENDEDPRICE NUMBER(12,2),
  L_DISCOUNT NUMBER(12,2),
  L_TAX NUMBER(12,2),
  L_RETURNFLAG VARCHAR(1),
  L_LINESTATUS VARCHAR(1),
  L_SHIPDATE DATE,
  L_COMMITDATE DATE,
  L_RECEIPTDATE DATE,
  L_SHIPINSTRUCT VARCHAR(25),
  L_SHIPMODE VARCHAR(10),
  L_COMMENT VARCHAR(44)
);
-- List files đã upload
LIST @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE
-- Load data từ stage vào tables
-- Create File Format 
CREATE OR REPLACE FILE FORMAT TPCH_ANALYTICS_DB.STAGING.FF_CSV_COMMA 
    TYPE = CSV 
    SKIP_HEADER = 1
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = 'AUTO';
-- Load bảng REGION 
COPY INTO TPCH_ANALYTICS_DB.STAGING.REGION
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_region.csv
FILE_FORMAT = FF_CSV_COMMA;
--check
SELECT * FROM TPCH_ANALYTICS_DB.STAGING.REGION 
LIMIT 10;
-- Load bảng NATION 
COPY INTO TPCH_ANALYTICS_DB.STAGING.NATION
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_nation.csv
FILE_FORMAT = FF_CSV_COMMA;
-- Load bảng CUSTOMER
COPY INTO TPCH_ANALYTICS_DB.STAGING.CUSTOMER
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_customer.csv
FILE_FORMAT = FF_CSV_COMMA;
-- Load bảng SUPPLIER
COPY INTO TPCH_ANALYTICS_DB.STAGING.SUPPLIER
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_supplier.csv
FILE_FORMAT = FF_CSV_COMMA;
-- Load bảng PART 
COPY INTO TPCH_ANALYTICS_DB.STAGING.PART
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_part.csv
FILE_FORMAT = FF_CSV_COMMA;
-- Load bảng PARTSUPP
COPY INTO TPCH_ANALYTICS_DB.STAGING.PARTSUPP
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_partsupp.csv
FILE_FORMAT = FF_CSV_COMMA;
-- Load bảng ORDERS
COPY INTO TPCH_ANALYTICS_DB.STAGING.ORDERS
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_orders.csv
FILE_FORMAT = FF_CSV_COMMA;
-- Load bảng LINEITEM
COPY INTO TPCH_ANALYTICS_DB.STAGING.LINEITEM
FROM @TPCH_ANALYTICS_DB.STAGING.TPCH_DATA_STAGE/tpch_sf1_line_item.csv.gz
FILE_FORMAT = FF_CSV_COMMA;
--Kiểm tra số dòng của các table 
SELECT COUNT(*) FROM STAGING.NATION;
SELECT COUNT(*) FROM STAGING.REGION;
SELECT COUNT(*) FROM STAGING.LINEITEM;
SELECT COUNT(*) FROM STAGING.CUSTOMER;
SELECT COUNT(*) FROM STAGING.ORDERS;
SELECT COUNT(*) FROM STAGING.PART;
SELECT COUNT(*) FROM STAGING.PARTSUPP;
SELECT COUNT(*) FROM STAGING.SUPPLIER;


