--3.1 Data Profiling
--Đếm số dòng mỗi bảng 
SELECT 'DIM_CUSTOMER' AS table_name, COUNT(*) AS row_count FROM DIM_CUSTOMER
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM DIM_DATE
UNION ALL
SELECT 'DIM_ORDER_ATTRIBUTE', COUNT(*) FROM DIM_ORDER_ATTRIBUTE
UNION ALL
SELECT 'DIM_ORDER_LINE_FULFILLMENT', COUNT(*) FROM DIM_ORDER_LINE_FULFILLMENT
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'DIM_SUPPLIER', COUNT(*) FROM DIM_SUPPLIER
UNION ALL
SELECT 'FACT_ORDER_LINE_ITEM', COUNT(*) FROM FACT_ORDER_LINE_ITEM;
--Phân tích khách hàng theo quốc gia 
SELECT 
    NATION_NAME,
    COUNT(DISTINCT CUSTOMER_KEY) AS CUSTOMER_COUNT
FROM DIM_CUSTOMER
GROUP BY NATION_NAME
ORDER BY CUSTOMER_COUNT DESC
-- Phân tích số lượng đơn hàng theo trạng thái
SELECT
    DIM.ORDER_STATUS,
    COUNT(DISTINCT ORDER_KEY) AS ORDER_COUNT
FROM FACT_ORDER_LINE_ITEM AS FACT
LEFT JOIN DIM_ORDER_ATTRIBUTE AS DIM
ON FACT.ORDER_ATTRIBUTE_KEY = DIM.ORDER_ATTRIBUTE_KEY
GROUP BY DIM.ORDER_STATUS
ORDER BY ORDER_COUNT DESC;
-- 4. Top 10 sản phẩm được bán nhiều nhất
SELECT 
    DIM.PRODUCT_NAME,
    COUNT(*) AS PRODUCT_COUNT
FROM FACT_ORDER_LINE_ITEM AS FACT
LEFT JOIN DIM_PRODUCT AS DIM
ON FACT.PRODUCT_KEY = DIM.PRODUCT_KEY
GROUP BY DIM.PRODUCT_NAME
ORDER BY PRODUCT_COUNT DESC
LIMIT 10
--3.2 Data Quality Checks
-- Kiểm tra NULL values
-- NULL check for DIM_CUSTOMER
SELECT
    COUNT(*) AS NULL_COUNT
FROM DIM_CUSTOMER
WHERE CUSTOMER_KEY IS NULL
   OR CUSTOMER_NAME IS NULL
   OR NATION_KEY IS NULL;
-- for DIM_PRODUCT
SELECT
    COUNT(*) AS NULL_COUNT
FROM DIM_PRODUCT
WHERE PRODUCT_KEY IS NULL
   OR PRODUCT_NAME IS NULL;
-- NULL check for DIM_ORDER_ATTRIBUTE
SELECT
    COUNT(*) AS NULL_COUNT
FROM DIM_ORDER_ATTRIBUTE
WHERE ORDER_ATTRIBUTE_KEY IS NULL
   OR ORDER_STATUS IS NULL;
-- NULL check for FACT_ORDER_LINE_ITEM
SELECT
    COUNT(*) AS NULL_COUNT
FROM FACT_ORDER_LINE_ITEM
WHERE ORDER_LINE_ITEM_KEY IS NULL
   OR ORDER_KEY IS NULL
   OR PRODUCT_KEY IS NULL
   OR CUSTOMER_KEY IS NULL
   OR ORDER_ATTRIBUTE_KEY IS NULL
   OR ORDER_LINE_FULFILLMENT_KEY IS NULL;
-- NULL check for SUPPLIER
SELECT
    COUNT(*) AS NULL_COUNT
FROM DIM_SUPPLIER
WHERE SUPPLIER_KEY IS NULL
    OR SUPPLIER_NAME IS NULL
    OR NATION_KEY IS NULL
-- NULL check for DIM_ORDER_LINE_FULFILLMENT
SELECT 
    COUNT(*) AS NULL_COUNT
FROM DIM_ORDER_LINE_FULFILLMENT
WHERE ORDER_LINE_FULFILLMENT_KEY IS NULL

-- Kiểm tra duplicates
-- Duplicate check for DIM_PRODUCT
SELECT
    PRODUCT_KEY,
    COUNT(*) AS DUP_COUNT
FROM DIM_PRODUCT
GROUP BY PRODUCT_KEY
HAVING COUNT(*) > 1;
-- Duplicate check for DIM_ORDER_ATTRIBUTE
SELECT
    ORDER_ATTRIBUTE_KEY,
    COUNT(*) AS DUP_COUNT
FROM DIM_ORDER_ATTRIBUTE
GROUP BY ORDER_ATTRIBUTE_KEY
HAVING COUNT(*) > 1;
-- Duplicate check for DIM_ORDER_LINE_FULFILLEMENT
SELECT
    ORDER_LINE_FULFILLMENT_KEY,
    COUNT(*) AS DUP_COUNT
FROM DIM_ORDER_LINE_FULFILLMENT
GROUP BY ORDER_LINE_FULFILLMENT_KEY
HAVING COUNT(*) > 1;
-- Duplicate check for DIM_SUPPLIER
SELECT
    SUPPLIER_KEY,
    COUNT(*) AS DUP_COUNT
FROM DIM_SUPPLIER
GROUP BY SUPPLIER_KEY
HAVING COUNT(*) > 1;
-- Duplicate check for DIM_CUSTOMER
SELECT
    CUSTOMER_KEY,
    COUNT(*) AS DUP_COUNT
FROM DIM_CUSTOMER
GROUP BY CUSTOMER_KEY
HAVING COUNT(*) > 1;
-- Duplicate check for FACT_ORDER_LINE_ITEM
SELECT
    ORDER_LINE_ITEM_KEY,
    COUNT(*) AS DUP_COUNT
FROM FACT_ORDER_LINE_ITEM
GROUP BY ORDER_LINE_ITEM_KEY,
HAVING COUNT(*) > 1;
--3.3 Performance Optimization với EXPLAIN
-- Sử dụng EXPLAIN để phân tích query execution plan
SELECT
    EXTRACT(YEAR  FROM D.DATE_ISO)  AS ORDER_YEAR,
    EXTRACT(MONTH FROM D.DATE_ISO)  AS ORDER_MONTH,
    O.ORDER_STATUS,
    COUNT(DISTINCT F.ORDER_KEY)      AS TOTAL_ORDERS,
    SUM(F.EXTENDED_PRICE)            AS TOTAL_REVENUE,
    AVG(F.EXTENDED_PRICE)            AS AVG_ORDER_VALUE,
    COUNT(DISTINCT F.CUSTOMER_KEY)   AS UNIQUE_CUSTOMERS
FROM FACT_ORDER_LINE_ITEM F
JOIN DIM_DATE D
    ON F.ORDER_DATE = D.DATE_ISO
JOIN DIM_ORDER_ATTRIBUTE O
    ON F.ORDER_ATTRIBUTE_KEY = O.ORDER_ATTRIBUTE_KEY
WHERE D.DATE_ISO >= '1995-01-01'
GROUP BY
    EXTRACT(YEAR  FROM D.DATE_ISO),
    EXTRACT(MONTH FROM D.DATE_ISO),
    O.ORDER_STATUS
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;
-- Using EXPLAIN to Understand Query Execution Plan
EXPLAIN 
SELECT
    EXTRACT(YEAR  FROM D.DATE_ISO)  AS ORDER_YEAR,
    EXTRACT(MONTH FROM D.DATE_ISO)  AS ORDER_MONTH,
    O.ORDER_STATUS,
    COUNT(DISTINCT F.ORDER_KEY)      AS TOTAL_ORDERS,
    SUM(F.EXTENDED_PRICE)            AS TOTAL_REVENUE,
    AVG(F.EXTENDED_PRICE)            AS AVG_ORDER_VALUE,
    COUNT(DISTINCT F.CUSTOMER_KEY)   AS UNIQUE_CUSTOMERS
FROM FACT_ORDER_LINE_ITEM F
JOIN DIM_DATE D
    ON F.ORDER_DATE = D.DATE_ISO
JOIN DIM_ORDER_ATTRIBUTE O
    ON F.ORDER_ATTRIBUTE_KEY = O.ORDER_ATTRIBUTE_KEY
WHERE D.DATE_ISO >= '1995-01-01'
GROUP BY
    EXTRACT(YEAR  FROM D.DATE_ISO),
    EXTRACT(MONTH FROM D.DATE_ISO),
    O.ORDER_STATUS
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;

