--4.1 Tạo Bảng với Sensitive Data
-- Tạo bảng customers với thông tin nhạy cảm
CREATE OR REPLACE TABLE CUSTOMER_SENSITIVE AS
SELECT
C.C_CUSTKEY,
C.C_NAME,
C.C_ADDRESS,
C.C_PHONE,
C.C_ACCTBAL,
N.N_NAME AS NATION,
R.R_NAME AS REGION,
C.C_MKTSEGMENT,
-- Thêm thông tin nhạy cảm (giả lập)
'customer_' || C.C_CUSTKEY || '@company.com' AS EMAIL,
LPAD(ABS(MOD(C.C_CUSTKEY * 123456789, 1000000000)), 9, '0') AS SSN_LAST_9
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER C
JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN TPCH_ANALYTICS_DB.STAGING.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;
--4.2 Tạo Masking Policies
-- Masking policy cho EMAIL
CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (val STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'TPCH_ADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('TPCH_ANALYST') THEN 
            REGEXP_REPLACE(val, '(^[^@]{2})[^@]+', '\\1***')  -- Show first 2 chars before @
        ELSE '***@company.com'
    END;
-- Masking policy cho PHONE
CREATE OR REPLACE MASKING POLICY MASK_PHONE AS (val STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'TPCH_ADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('TPCH_ANALYST') THEN 
            'XXX-XXX-' || RIGHT(val, 4)
        ELSE 'XX-XXX-XXX-XXXX'
    END;
-- Masking policy cho SSN
CREATE OR REPLACE MASKING POLICY MASK_SSN AS (val STRING) RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'TPCH_ADMIN') THEN val
        ELSE '***-**-****'
    END;
-- Masking policy cho ACCOUNT BALANCE
CREATE OR REPLACE MASKING POLICY MASK_ACCTBAL AS (val NUMBER) 
RETURNS NUMBER ->
  CASE 
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'TPCH_ADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('TPCH_ANALYST') THEN 
            CASE
                WHEN val < 1000 THEN 1000
                ELSE FLOOR(val / 1000) * 1000
            END
        ELSE NULL
    END;
-- Grant SELECT on customer sensitive table
GRANT SELECT ON TABLE CUSTOMER_SENSITIVE TO ROLE TPCH_ADMIN;
GRANT SELECT ON TABLE CUSTOMER_SENSITIVE TO ROLE TPCH_ANALYST;
GRANT SELECT ON TABLE CUSTOMER_SENSITIVE TO ROLE TPCH_VIEWER;
--  Apply Masking Policies to Table Columns
ALTER TABLE CUSTOMER_SENSITIVE 
    MODIFY COLUMN EMAIL SET MASKING POLICY MASK_EMAIL;
ALTER TABLE CUSTOMER_SENSITIVE 
    MODIFY COLUMN C_PHONE SET MASKING POLICY MASK_PHONE;
ALTER TABLE CUSTOMER_SENSITIVE 
    MODIFY COLUMN SSN_LAST_9 SET MASKING POLICY MASK_SSN;
ALTER TABLE CUSTOMER_SENSITIVE 
    MODIFY COLUMN C_ACCTBAL SET MASKING POLICY MASK_ACCTBAL;
-- Test Masking Policies with Different Roles
-- View all masking policies
SHOW MASKING POLICIES;

-- Describe table to see which columns have masking policies
DESCRIBE TABLE CUSTOMER_SENSITIVE;

-- Test as TPCH_ADMIN (sees everything)
USE ROLE TPCH_ADMIN;
SELECT 
    EMAIL,
    C_PHONE,
    SSN_LAST_9,
    C_ACCTBAL
FROM CUSTOMER_SENSITIVE;

-- Test as ROLE_ANALYST (sees partial data)
USE ROLE TPCH_ANALYST;
SELECT 
    EMAIL,
    C_PHONE,
    SSN_LAST_9,
    C_ACCTBAL
FROM CUSTOMER_SENSITIVE;

-- Test as ROLE_VIEWER (most data masked)
USE ROLE TPCH_VIEWER;
SELECT 
    EMAIL,
    C_PHONE,
    SSN_LAST_9,
    C_ACCTBAL
FROM CUSTOMER_SENSITIVE;

-- Switch back to ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;
GRANT ROLE TPCH_ADMIN TO USER MINH1999;
GRANT ROLE TPCH_ANALYST TO USER MINH1999;
GRANT ROLE TPCH_VIEWER TO USER MINH1999;
-- SECURE DATA SHARING
-- Create a clean, curated view for sharing (without sensitive data)
CREATE OR REPLACE SECURE VIEW VW_CUSTOMER_PUBLIC AS
SELECT 
    C_CUSTKEY,
    C_NAME,
    C_ADDRESS,
    NATION,
    REGION,
    C_MKTSEGMENT,
FROM CUSTOMER_SENSITIVE;
-- Create aggregated view (safe for external sharing)
CREATE OR REPLACE SECURE VIEW VW_CUSTOMER_SUMMARY AS
SELECT 
    NATION,
    COUNT(*) AS TOTAL_CUSTOMERS,
    AVG(C_ACCTBAL) AS AVG_ACCTBAL_RANGE,
FROM CUSTOMER_SENSITIVE
GROUP BY NATION;
-- Verify views
SELECT * FROM VW_CUSTOMER_PUBLIC;
SELECT * FROM VW_CUSTOMER_SUMMARY;
-- Create Secure Share
-- Create a share (container for sharing objects)
CREATE OR REPLACE SHARE SHARE_CUSTOMER_DATA
    COMMENT = 'Curated customer data for external partners';

-- Grant usage on database to share
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO SHARE SHARE_CUSTOMER_DATA;

-- Grant usage on schema to share
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO SHARE SHARE_CUSTOMER_DATA;

-- Grant SELECT on views to share (NOT raw tables!)
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.STAGING.VW_CUSTOMER_PUBLIC 
    TO SHARE SHARE_CUSTOMER_DATA;

GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.STAGING.VW_CUSTOMER_SUMMARY 
    TO SHARE SHARE_CUSTOMER_DATA;
-- Manage and Monitor Share
-- ============================================================================

-- View all shares
SHOW SHARES;

-- Describe share contents
DESC SHARE SHARE_CUSTOMER_DATA;

-- Add consumer account (in production, replace with actual consumer account)
ALTER SHARE SHARE_CUSTOMER_DATA ADD ACCOUNTS = ****;